# Generated by Django 5.0.6 on 2024-07-03 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTable',
            fields=[
                ('postId', models.AutoField(db_column='postID', primary_key=True, serialize=False)),
                ('postTitle', models.CharField(db_column='postTitle', max_length=255)),
                ('postContent', models.TextField(db_column='postContent')),
                ('postCreatedAt', models.DateTimeField(auto_now_add=True, db_column='postCreatedAt')),
                ('postUpdatedAt', models.DateTimeField(auto_now=True, db_column='postUpdatedAt')),
                ('categoryId', models.ForeignKey(db_column='catID', on_delete=django.db.models.deletion.DO_NOTHING, to='category.categorytable')),
                ('userId', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.DO_NOTHING, to='user.usertable')),
            ],
            options={
                'db_table': 'postTable',
            },
        ),
    ]
