# Generated by Django 5.0.6 on 2024-07-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTable',
            fields=[
                ('catigoryId', models.AutoField(db_column='catID', primary_key=True, serialize=False)),
                ('catigoryName', models.CharField(db_column='catName', max_length=50)),
            ],
            options={
                'db_table': 'tblCategory',
            },
        ),
    ]
