# Generated by Django 5.0.6 on 2024-07-03 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTagTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postId', models.ForeignKey(db_column='postID', on_delete=django.db.models.deletion.CASCADE, to='posts.posttable')),
                ('tagId', models.ForeignKey(db_column='tagID', on_delete=django.db.models.deletion.CASCADE, to='tag.tagtable')),
            ],
            options={
                'db_table': 'tblPostTag',
            },
        ),
    ]
