# Generated by Django 5.0.6 on 2024-07-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('userId', models.AutoField(db_column='userId', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='userName', max_length=50)),
                ('email', models.CharField(db_column='userEmail', max_length=255)),
                ('password', models.CharField(db_column='userPassword', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='userCreatedAt')),
            ],
            options={
                'db_table': 'tblUser',
            },
        ),
    ]
