# Generated by Django 5.0.6 on 2024-07-03 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentTable',
            fields=[
                ('commentId', models.AutoField(db_column='commentID', primary_key=True, serialize=False)),
                ('content', models.TextField(db_column='commentContent')),
                ('createdTime', models.DateTimeField(db_column='commentCreatedAt')),
                ('postId', models.ForeignKey(db_column='postID', on_delete=django.db.models.deletion.CASCADE, to='posts.posttable')),
                ('userId', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to='user.usertable')),
            ],
            options={
                'db_table': 'tblComment',
            },
        ),
    ]
